source 'https://github.com/CocoaPods/Specs.git'

target 'BABFrameObservingInputAccessoryView', :exclusive => true do
  pod "BABFrameObservingInputAccessoryView", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "BABFrameObservingInputAccessoryView", :path => "../"

  
end
